data_ingestion:
  test_size: 0.2

model_building:
  random_forest:
    n_estimators: 100
    max_depth: 10
    # random_state: 42
    # n_jobs: -1 
  logistic_regression:
    # penalty: l2
    C: 1.0
    max_iter: 200
    random_state: 42
  xgboost:
    n_estimators: 100
    learning_rate: 0.1
    subsample: 0.8
    colsample_bytree: 0.8
    max_depth: 6